#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f risc_v.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace risc_v.sv --exe risc_v_tb.cpp #creates the VERILATED files starting with V

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vrisc_v.mk Vrisc_v

# run executable simulation file
obj_dir/Vrisc_v