#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f topPC.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace topPC.sv --exe topPC_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VtopPC.mk VtopPC

# run executable simulation file
obj_dir/VtopPC