name: Build Verilator simulation file

on: [push, pull_request]

jobs:
  ubuntu:
    strategy:
      matrix:
        runner: [ubuntu-20.04]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout Lab4-Reduced-RISC-V
        uses: actions/checkout@v2
        with:
          path: Lab4-Reduced-RISC-V
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 2
      - name: Create environment
        run: bash <(curl -fsSL https://raw.githubusercontent.com/EIE2-IAC-Labs/Lab0-devtools/main/tools/install.sh)
      - name: Build and Run Simulation
        run: |
          chmod +x Lab4-Reduced-RISC-V/doit.sh
          cd Lab4-Reduced-RISC-V
          ./doit.sh
          
  mac_os:
    runs-on: macos-12
    steps:
      - name: Checkout Lab4-Reduced-RISC-V
        uses: actions/checkout@v2
        with:
          path: Lab4-Reduced-RISC-V
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 2
      - name: Create environment
        run: bash <(curl -fsSL https://raw.githubusercontent.com/EIE2-IAC-Labs/Lab0-devtools/main/tools/install.sh)
      - name: Build and Run Simulation
        run: |
          chmod +x Lab4-Reduced-RISC-V/doit.sh
          cd Lab4-Reduced-RISC-V
          ./doit.sh
